services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: jungle_gaming_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d jungle_gaming_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:4.14.0
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sqs
      - DEBUG=1
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - "start-dev"
      - "--import-realm"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"

  migrate:
      build:
        context: .
        dockerfile: Dockerfile
      command: [ "/app/migrate", "up" ]
      env_file:
        - .env
      depends_on:
        postgres:
          condition: service_healthy

  api-1:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "/app/api" ]
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      keycloak:
        condition: service_started
      migrate:
        condition: service_completed_successfully

  api-2:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "/app/api" ]
    ports:
      - "4001:4000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      keycloak:
        condition: service_started
      migrate:
        condition: service_completed_successfully

  consumer-1:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "/app/consumer" ]
    env_file:
      - .env
    environment:
      - CONSUMER_NAME=worker-consumer-1
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  consumer-2:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "/app/consumer" ]
    env_file:
      - .env
    environment:
      - CONSUMER_NAME=worker-consumer-2
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "/app/publisher" ]
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  pgdata:
  localstack-data: